[ClassVersion("0.1.0"), FriendlyName("cVstsAgent")]
class cVstsAgent : OMI_BaseResource
{
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [Key] string Name;
  [Required] string AgentFolder;
  [Required] string ServerUrl;
  [write, EmbeddedInstance("MSFT_Credential")] string Token;
  [write, EmbeddedInstance("MSFT_Credential")] string ServiceCredentials;
  [write] string PoolName;
  [write] string LocalAgentSource;
  [write] string WorkFolder;
};